# Generated by Django 5.1.5 on 2025-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_editprofile_model_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile_model',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
