# Generated by Django 5.1.5 on 2025-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_editprofile_model_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile_model',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
