# Generated by Django 5.1.5 on 2025-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_editprofile_model_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile_model',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
