# Generated by Django 5.1.5 on 2025-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_model_delete_editprofile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
