# Generated by Django 5.1.5 on 2025-02-04 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article_models_delete_article_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Models',
            new_name='Article_Model',
        ),
    ]
