# Generated by Django 5.1.5 on 2025-02-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_article_models_article_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_model',
            old_name='body',
            new_name='main',
        ),
    ]
