# Generated by Django 5.1.5 on 2025-02-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_body_article_model_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_model',
            old_name='main',
            new_name='body',
        ),
    ]
