# Generated by Django 5.1.5 on 2025-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_main_article_model_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_model',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
