# Generated by Django 5.1.5 on 2025-02-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_article_model_like_article_model_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_model',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
