# Generated by Django 5.1.5 on 2025-02-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_article_model_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_model',
            old_name='view',
            new_name='views',
        ),
    ]
