# Generated by Django 5.1.5 on 2025-02-07 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_view_article_model_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article_model',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
