# Generated by Django 5.1.5 on 2025-02-07 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_article_model_save'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_model',
            name='save',
        ),
        migrations.AddField(
            model_name='article_model',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
