# Generated by Django 5.1.5 on 2025-02-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_model',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment_model'),
        ),
    ]
